<link href="system/styles/default2.css" rel="stylesheet" type="text/css" />
<link type="text/css" href="system/styles/wforms.css" rel="stylesheet" />
<link type="text/css" href="system/styles/wforms-jsonly.css" rel="alternate stylesheet" title="stylesheet activated by javascript" />
<link type="text/css" href="system/styles/tabber.css" rel="stylesheet" media="screen">

<style type="text/css">

form.cmxform { width: 97%;	}	
form.cmxform label { width: 80px; }
form.cmxform label.preField { width: expression('4em'); min-width: 4em }
form.cmxform fieldset fieldset { background: none; }	
form.cmxform fieldset li {	
	padding: 3px 10px 3px;
	/*background: url(images/form/cmxform-divider.gif) left bottom repeat-x;*/
}
</style>


<script type="text/javascript" src="system/scripts/jquery.js"></script> 
<script type="text/javascript" src="system/scripts/wforms.js"></script> 
<script type="text/javascript" src="system/scripts/cmxform.js"></script>
<script type="text/javascript" src="system/scripts/tabber.js"></script>
<script type="text/javascript" src="system/scripts/utility.js"></script>
